version: '3'
services:
 app:
    build: .
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 150M
    networks:
      - backend

 nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "3036:80"
    depends_on:
      - app
    networks:
      - backend

networks:
 backend:
